#####################
# Generate new data #
#####################

Data:
  # Generate_new_data: true

  data_mode: 'train' # 'train' / 'val' / 'test'
  noise: false
  store_doa: true

  # Data args:
  path:
    raw: '/mnt/dsi_vol1/shared/sharon_db/wsj'
    raw_noise: '/mnt/dsi_vol1/shared/sharon_db/wham_noise'
  
  results_path:
    raw: '/home/dsi/ziniroi/roi-aviad/data/raw'
    train: '/home/dsi/ziniroi/roi-aviad/data/raw/train'
    val: '/home/dsi/ziniroi/roi-aviad/data/raw/val'
    test: '/home/dsi/ziniroi/roi-aviad/data/raw/test'
    featuers: '/home/dsi/ziniroi/roi-aviad/data/processed/features'
  
  num_results: 
    train: 25000
    val: 5000
    test: 5000
  
  # speakers:
  fixed_num_of_speakers: true
  max_speakers: 2  # relevant only to the random version(fixed_num_of_speakers=false)
  spekers_number: 2

  # mics:
  num_of_mics: 4
  mic_array_dist: [0.08,0.08,0.08] # relative distances

  sir: 0
  max_rt60: 0.2
  snr: 20
  

